# This is a basic workflow to help you get started with Actions
name: Build LaTeX document

# Controls when the workflow will run
on:
  push:
    paths:
    - 'papers/report.tex'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: papers
          root_file: report.tex
      - name: Copy PDF file
        run: mkdir docs && cp papers/*.pdf docs/
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
