# This is a basic workflow to help you get started with Actions
name: Build LaTeX document

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "papers/report.tex"
      - "papers/beamer.tex"
  push:
    branches:
      - main
      - develop
    paths:
      - "papers/report.tex"
      - "papers/beamer.tex"

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.file_changes.outputs.files }}
    steps:
      - uses: actions/checkout@v2
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        
  compile_paper:
    needs: precheck
    runs-on: ubuntu-latest
    if: contains(fromJson(needs.precheck.outputs.files_changed), 'papers/report.tex')
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile report.tex
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: papers
          root_file: report.tex
      - name: Copy report.pdf
        run: mkdir docs && cp papers/report.pdf docs/
      - name: Deploy report.pdf
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages-paper
          
  compile_beamer:
    needs: precheck
    runs-on: ubuntu-latest
    if: contains(fromJson(needs.precheck.outputs.files_changed), 'papers/beamer.tex')
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile beamer.tex
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: papers
          root_file: beamer.tex
      - name: Copy beamer.pdf
        run: mkdir beamer && cp papers/beamer.pdf beamer/
      - name: Deploy beamer.pdf
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./beamer
          publish_branch: gh-pages-beamer
