# This is a basic workflow to help you get started with Actions
name: Build LaTeX document

# Controls when the workflow will run
on:
  push:
    paths:
    - "papers/report.tex"
    - "papers/presentations.tex"

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.file_changes.outputs.files }}
    steps:
      - uses: actions/checkout@v2
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        
  build_latex:
    needs: precheck
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile report.tex
        if: contains(fromJson(needs.precheck.outputs.files_changed), 'papers/report.tex')
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: papers
          root_file: report.tex
      - name: Copy report.pdf
        if: contains(fromJson(needs.precheck.outputs.files_changed), 'papers/report.tex')
        run: mkdir docs && cp papers/report.pdf docs/
      - name: Deploy report.pdf
        if: contains(fromJson(needs.precheck.outputs.files_changed), 'papers/report.tex')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages-paper
      - name: Compile presentation.tex
        if: contains(steps.changed-files.outputs.modified_files, 'papers/presentation.tex')
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: papers
          root_file: presentation.tex
      - name: Copy presentation.pdf
        if: contains(fromJson(needs.precheck.outputs.files_changed), 'papers/presentation.tex')
        run: mkdir beamer && cp papers/presentation.pdf beamer/
      - name: Deploy presentation.pdf
        if: contains(fromJson(needs.precheck.outputs.files_changed), 'papers/presentation.tex')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./beamer
          publish_branch: gh-pages-beamer
